/* EVALUX · pantallas del docente */
const misEx=()=>S.examenes.filter(e=>e.docente===S.yo.id);
const misGrupos=()=>S.grupos.filter(g=>g.docente===S.yo.id);
const nEst=e=>new Set(e.grupos.flatMap(g=>(S.grupos.find(x=>x.id===g)||{est:[]}).est)).size;
const estDe=id=>S.estudiantes.find(x=>x.id===id)||{id,nombre:'Estudiante retirado',correo:'',codigo:'—',prog:'',fac:'',semestre:''};
const grupoTxt=id=>{const g=S.grupos.find(x=>x.id===id);return g?`${g.asig} · Grupo ${g.codigo}`:''};
function stats(e){const filas=Object.keys(S.intentos).filter(k=>k.startsWith(e.id+'|')).map(k=>({s:estDe(k.split('|')[1]),...S.intentos[k]})).filter(f=>f.nota!=null&&f.estado==='entregado');
 const sos=Object.keys(S.intentos).filter(k=>k.startsWith(e.id+'|')&&S.intentos[k].estado==='sospecha').map(k=>({s:estDe(k.split('|')[1]),...S.intentos[k]}));
 const n=filas.length,prom=n?filas.reduce((a,f)=>a+f.nota,0)/n:0,aprob=filas.filter(f=>f.nota>=S.cfg.aprueba).length;
 const porPreg=e.preg.map(q=>{let ok=0;const dist=q.tipo==='sel'?q.opts.map(()=>0):null;filas.forEach(f=>{const r=f.respuestas[q.id];ok+=puntaje(q,r,f);if(dist&&r!=null&&dist[r]!=null)dist[r]++});return{q,pct:n?ok/n*100:0,dist}});
 return{filas,sos,n,prom,aprob,porPreg}}
const tieneImg=e=>e.preg.some(q=>(q.imgs||[]).length||(q.optImgs||[]).some(Boolean)||(q.parImgs||[]).some(Boolean));
function ticket(e,acts){const st=estadoExamen(e),d=e.apertura?new Date(e.apertura):null;
 return `<article class="ticket" style="--tk:${TK_EX[st]}"><div class="date">${d?`<span class="d">${d.getDate()}</span><span class="m">${mes(d)}</span><span class="h">${hora(d)}</span>`:`<span class="d">${ic('edit')}</span><span class="m">Borrador</span>`}</div>
 <div class="info"><div class="row" style="gap:8px"><span class="chip">${esc(e.asig)}</span><span class="pill ${PILL_EX[st]}"><i></i>${cap(st)}</span>${bloqueado(e)?`<span class="pill p-mute" title="Ya fue presentado">${ic('lock','sm')}Bloqueado</span>`:''}</div>
 <h3>${esc(e.titulo)}</h3><div class="meta"><span>${ic('exam','sm')}${e.preg.length} pregunta${e.preg.length===1?'':'s'}</span><span>${ic('clock','sm')}${e.dur} min</span><span>${ic('group','sm')}${e.grupos.map(g=>'Grupo '+esc((S.grupos.find(x=>x.id===g)||{}).codigo||'')).join(', ')||'Sin grupo'}</span>${tieneImg(e)?`<span>${ic('image','sm')}Con imágenes</span>`:''}</div>
 <div class="row" style="gap:6px;margin-top:2px">${acts}</div></div></article>`}
function semana(){const dias=[...Array(7)].map((_,i)=>{const d=ahora();d.setHours(0,0,0,0);return addMin(d,i*1440)});
 return `<div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px">${dias.map((d,i)=>{const ex=misEx().filter(e=>e.apertura&&new Date(e.apertura).toDateString()===d.toDateString());return `<div style="border:1px solid var(--line);border-radius:14px;padding:8px 4px;text-align:center;background:${i===0?'var(--brand-soft)':'var(--surface-2)'};min-width:0"><div class="small muted" style="text-transform:capitalize">${d.toLocaleDateString('es-CO',{weekday:'short'}).replace('.','')}</div><b style="font-size:1.2rem">${d.getDate()}</b><div style="display:flex;gap:3px;justify-content:center;margin-top:4px;min-height:8px">${ex.map(e=>`<i title="${esc(e.titulo)}" style="width:8px;height:8px;border-radius:50%;background:${TK_EX[estadoExamen(e)]}"></i>`).join('')}</div></div>`}).join('')}</div>`}
function vDocInicio(){const d=doc(),ex=misEx(),enCurso=ex.filter(e=>estadoExamen(e)==='en curso'),prox=ex.filter(e=>estadoExamen(e)==='programado').sort((a,b)=>new Date(a.apertura)-new Date(b.apertura)),cer=ex.filter(e=>estadoExamen(e)==='cerrado').sort((a,b)=>new Date(b.apertura)-new Date(a.apertura)),c=cer[0],r=c?stats(c):null;
 const g0=misGrupos()[0],gl=g0?cer.filter(e=>e.grupos.includes(g0.id)).slice().reverse():[];
 const pasos=[[misGrupos().length>0,'Cree un grupo','grupos'],[misGrupos().some(g=>g.est.length),'Agregue estudiantes','grupos'],[ex.length>0,'Cree su primer examen','examenes']];
 return `${hero('Docente','Hola, '+esc(d.nombres.split(' ')[0]),'Sus asignaturas: '+d.asig.map(esc).join(' · '),`<button class="btn pri" data-act="ex-new">${ic('plus','sm')}Crear examen</button><button class="btn" data-act="nav" data-v="reportes">${ic('chart','sm')}Reportes</button>`,'edit')}
 ${pasos.some(p=>!p[0])?`<div class="card" style="display:flex;flex-direction:column;gap:12px;border-left:6px solid var(--brand)"><h3>Para empezar</h3><div class="grid2" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">${pasos.map(([ok,t,v],i)=>`<button class="card row" data-act="nav" data-v="${v}" style="all:unset;cursor:pointer;display:flex;gap:12px;align-items:center;padding:14px;border:1px solid var(--line);border-radius:16px;background:${ok?'var(--ok-soft)':'var(--surface-2)'}"><span class="q-n" style="background:${ok?'var(--ok)':'var(--brand)'}">${ok?'✓':i+1}</span><b>${t}</b></button>`).join('')}</div></div>`:''}
 ${enCurso.map(e=>`<div class="card" style="display:flex;gap:18px;align-items:center;flex-wrap:wrap;border:2px solid var(--coral)">${ring(presentados(e)/Math.max(1,nEst(e)),'var(--coral)',86,10,presentados(e)+'/'+nEst(e))}<div style="flex:1 1 240px;min-width:0"><span class="pill p-hot live"><i></i>En curso ahora</span><h3 style="margin-top:8px">${esc(e.titulo)}</h3><p class="small muted">Termina para todos a las ${hora(cierre(e))} · han entrado ${presentados(e)} de ${nEst(e)} estudiantes</p></div><button class="btn hot" data-act="ex-sala" data-id="${e.id}">${ic('eye','sm')}Abrir sala en vivo</button></div>`).join('')}
 <div class="bento">${tile('group','c1','Grupos',misGrupos().length,misGrupos().reduce((a,g)=>a+g.est.length,0)+' estudiantes')}${tile('exam','c2','Exámenes',ex.length,ex.filter(e=>estadoExamen(e)==='borrador').length+' en borrador')}${tile('bank','c4','Banco de preguntas',S.banco.length,'listas para reutilizar')}${r&&r.n?tile('trend','cok','Último promedio',nota1(r.prom),r.aprob+' de '+r.n+' aprobaron'):tile('trend','cok','Último promedio','—','aún sin exámenes cerrados')}
 <div class="card s7"><div class="card-h"><span class="chipi cb">${ic('cal')}</span><h3>Esta semana</h3></div>${semana()}<div class="legend" style="margin-top:12px"><span style="--c:#E0562F">En curso</span><span style="--c:#2B3A8C">Programado</span><span style="--c:#1F7A4D">Cerrado</span></div></div>
 <div class="card s5"><div class="card-h"><span class="chipi c3">${ic('trend')}</span><h3>Evolución${g0?' · '+esc(g0.asig)+' '+esc(g0.codigo):''}</h3></div>${gl.length?linea([{n:'Promedio del grupo',c:'var(--brand)',v:gl.map(e=>stats(e).prom)}],gl.map(e=>fcorta(e.apertura)),{h:210}):'<p class="muted">Aparece cuando tenga exámenes cerrados.</p>'}</div></div>
 ${prox.length||c?`<h2>Próximos y recientes</h2><div class="grid2">${prox.slice(0,2).map(e=>ticket(e,bloqueado(e)?'':`<button class="btn sm" data-act="ex-edit" data-id="${e.id}">${ic('edit','sm')}Editar</button>`)).join('')}${c?ticket(c,`<button class="btn sm pri" data-act="ex-res" data-id="${c.id}">${ic('chart','sm')}Ver resultados</button>`):''}</div>`:''}`}

/* ---------- grupos ---------- */
function vGrupos(){const gs=misGrupos();if(!S.grupoSel||!gs.find(g=>g.id===S.grupoSel))S.grupoSel=gs[0]&&gs[0].id;const g=gs.find(x=>x.id===S.grupoSel),q=norm(S.fEst||'');
 const ests=g?g.est.map(estDe).filter(s=>!q||norm(s.nombre+' '+s.codigo+' '+s.correo).includes(q)):[];
 const promE=sid=>{const ns=S.examenes.filter(e=>g&&e.grupos.includes(g.id)).map(e=>S.intentos[e.id+'|'+sid]).filter(it=>it&&it.nota!=null).map(it=>it.nota);return promedio(ns)};
 return `${hero('Docente','Mis grupos','Cada grupo pertenece a una de sus asignaturas. El estudiante entra con su correo y su código como contraseña.',`<button class="btn pri" data-act="grp-new">${ic('plus','sm')}Crear grupo</button>`,'group')}
 ${gs.length?`<div class="grid2" role="group" aria-label="Grupos">${gs.map((x,i)=>`<button data-act="grp-sel" data-id="${x.id}" aria-pressed="${x.id===S.grupoSel}" style="all:unset;cursor:pointer;background:var(--surface);border:2px solid ${x.id===S.grupoSel?'var(--brand)':'var(--line)'};border-radius:22px;padding:18px;display:flex;gap:14px;align-items:center;box-shadow:var(--shadow)"><span class="avatar" style="width:52px;height:52px;background:${PALHEX[i%PALHEX.length]};font-size:1.05rem;border-radius:16px">${esc(x.codigo)}</span><span style="min-width:0"><b>${esc(x.asig)}</b><br><span class="small muted">Grupo ${esc(x.codigo)} · ${x.est.length} estudiante${x.est.length===1?'':'s'} · ${esc(x.periodo)}</span></span></button>`).join('')}</div>`:''}
 ${g?`<div class="card" style="display:flex;flex-direction:column;gap:16px"><div class="row"><div><h2>${esc(g.asig)} · Grupo ${esc(g.codigo)}</h2><div class="small muted">Periodo ${esc(g.periodo)} · ${g.est.length} estudiantes</div></div><span class="spacer"></span><button class="btn sm ghost danger" data-act="grp-del">${ic('trash','sm')}Eliminar grupo</button><button class="btn" data-act="est-bulk">${ic('upload','sm')}Cargar desde Excel</button><button class="btn pri" data-act="est-new">${ic('plus','sm')}Agregar estudiante</button></div>
 <div style="position:relative"><input type="search" id="f-est" placeholder="Buscar por nombre, código o correo" value="${esc(S.fEst||'')}" aria-label="Buscar estudiantes" style="padding-left:42px"><span style="position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--muted)">${ic('search','sm')}</span></div>
 <div class="tbl-wrap" style="box-shadow:none"><table><thead><tr><th>Estudiante</th><th>Código</th><th>Programa</th><th class="num">Semestre</th><th class="num">Promedio</th><th class="num"></th></tr></thead><tbody>${ests.length?ests.map(s=>{const p=promE(s.id);return `<tr><td><div class="person">${avatar(s.nombre)}<div style="min-width:0"><b>${esc(s.nombre)}</b><div class="small muted">${esc(s.correo)}</div></div></div></td><td class="mono">${esc(s.codigo)}</td><td>${esc(s.prog)}<div class="small muted">${esc(s.fac)}</div></td><td class="num">${esc(s.semestre)}.°</td><td class="num">${p!=null?`<b>${nota1(p)}</b> ${lvTag(p)}`:'<span class="muted">—</span>'}</td><td class="num"><button class="btn sm ghost" data-act="est-quitar" data-id="${s.id}">Quitar</button></td></tr>`}).join(''):`<tr><td colspan="6"><div class="empty">${ic('users','lg')}No hay estudiantes${q?' que coincidan':''}. Agréguelos uno por uno o desde Excel.</div></td></tr>`}</tbody></table></div></div>`:`<div class="card empty">${ic('group','lg')}<b>Cree su primer grupo</b><span class="small">Luego agregue a los estudiantes uno por uno o desde Excel.</span><button class="btn pri" data-act="grp-new">${ic('plus','sm')}Crear grupo</button></div>`}`}
function formEstudiante(){const progs=Object.keys(S.FAC).map(f=>`<optgroup label="${esc(f)}">${S.FAC[f].map(p=>`<option ${p===doc().prog?'selected':''}>${esc(p)}</option>`).join('')}</optgroup>`).join('');
 modal({title:'Agregar estudiante',icon:['user','c3'],body:`<form id="fe" class="form-grid" novalidate>
 <label class="field" style="grid-column:1/-1"><span>Nombres y apellidos</span><input type="text" id="fe-nombre"></label>
 <label class="field"><span>Correo institucional</span><input type="email" id="fe-correo" placeholder="nombre@uniguajira.edu.co"></label>
 <label class="field"><span>Código</span><input type="text" inputmode="numeric" id="fe-codigo"><small class="hint">Es su contraseña y no se cambia. De 6 a 15 números.</small></label>
 <label class="field"><span>Programa</span><select id="fe-prog">${progs}</select><small class="hint" id="fe-fac">Facultad: ${esc(facDe(doc().prog)||'')}</small></label>
 <label class="field"><span>Semestre</span><select id="fe-sem">${Array.from({length:12},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label>
 <div id="fe-err" class="issues" role="alert" style="grid-column:1/-1" hidden></div></form>`,foot:`<button class="btn" data-act="close">Cancelar</button><button class="btn pri" data-act="est-save">${ic('plus','sm')}Agregar al grupo</button>`})}
async function guardarEstudiante(btn){const v=k=>$('#fe-'+k).value.trim(),errs=[];
 if(!v('nombre'))errs.push('Escriba nombres y apellidos.');if(!RX_MAIL.test(v('correo')))errs.push('Escriba un correo válido.');if(!/^\d{6,15}$/.test(v('codigo')))errs.push('El código solo lleva números (6 a 15).');
 const x=S.estudiantes.find(z=>z.codigo===v('codigo'));if(x&&norm(x.correo)!==norm(v('correo')))errs.push('Ese código ya está registrado con otro correo.');
 if(errs.length){const b=$('#fe-err');b.innerHTML='<b>Revise estos datos:</b><ul>'+errs.map(e=>`<li>${esc(e)}</li>`).join('')+'</ul>';b.hidden=false;return}
 await ocupado(btn,async()=>{const r=await usuarios({accion:'agregar_estudiantes',grupo_id:S.grupoSel,personas:[{nombres:v('nombre'),email:v('correo'),codigo:v('codigo'),programa:v('prog'),semestre:+v('sem')}]});
  if(r.errores&&r.errores.length){const b=$('#fe-err');b.innerHTML='<b>No se pudo agregar:</b><ul>'+r.errores.map(e=>`<li>${esc(e.error)}</li>`).join('')+'</ul>';b.hidden=false;return}
  closeModal();await refrescar();toast(r.agregados[0]&&r.agregados[0].nuevo?'Estudiante agregado. Entra con su correo y su código.':'El estudiante ya tenía cuenta: se agregó a este grupo')})}
function formGrupo(){const d=doc();modal({title:'Crear grupo',size:'sm',icon:['group','c1'],body:`<form id="fg" class="form-grid" novalidate><label class="field" style="grid-column:1/-1"><span>Asignatura</span><select id="fg-asig">${d.asig.map(a=>`<option>${esc(a)}</option>`).join('')}</select></label>
 <label class="field"><span>Código del grupo</span><input type="text" id="fg-cod" placeholder="01" maxlength="12"></label><label class="field"><span>Periodo</span><input type="text" id="fg-per" value="${esc(S.cfg.periodo)}"></label><p class="err" id="fg-err" hidden style="grid-column:1/-1"></p></form>`,foot:`<button class="btn" data-act="close">Cancelar</button><button class="btn pri" data-act="grp-save">Crear grupo</button>`})}
async function guardarGrupo(btn){const c=$('#fg-cod').value.trim(),a=$('#fg-asig').value,p=$('#fg-per').value.trim(),er=$('#fg-err');
 if(!c||!p){er.textContent='Escriba el código del grupo y el periodo.';er.hidden=false;return}
 if(misGrupos().some(g=>g.asig===a&&g.codigo===c&&g.periodo===p)){er.textContent='Ya tiene ese grupo en esa asignatura y periodo.';er.hidden=false;return}
 await ocupado(btn,async()=>{const g=await q(sb.from('grupos').insert({docente_id:S.yo.id,asignatura:a,codigo:c,periodo:p}).select().single());S.grupoSel=g.id;closeModal();await refrescar();toast('Grupo creado')})}

/* ---------- exámenes ---------- */
function vExamenes(){const f=S.exFiltro,ex=misEx().filter(e=>f==='todos'||estadoExamen(e)===f),cnt=k=>misEx().filter(e=>estadoExamen(e)===k).length;
 return `${hero('Docente','Exámenes','Un examen presentado queda bloqueado para no alterar las notas. Para corregirlo, duplíquelo.',`<button class="btn pri" data-act="ex-new">${ic('plus','sm')}Crear examen</button>`,'exam')}
 <div class="seg" role="group" aria-label="Filtrar exámenes">${[['todos','Todos',misEx().length],['en curso','En curso',cnt('en curso')],['programado','Programados',cnt('programado')],['borrador','Borradores',cnt('borrador')],['cerrado','Cerrados',cnt('cerrado')]].map(([k,l,n])=>`<button data-act="ex-filtro" data-v="${k}" aria-pressed="${f===k}">${l} · ${n}</button>`).join('')}</div>
 <div class="grid2">${ex.map(e=>{const st=estadoExamen(e),lock=bloqueado(e);return ticket(e,`${st==='en curso'?`<button class="btn sm hot" data-act="ex-sala" data-id="${e.id}">${ic('eye','sm')}Sala en vivo</button>`:''}${lock||st==='cerrado'?`<button class="btn sm pri" data-act="ex-res" data-id="${e.id}">${ic('chart','sm')}Resultados</button>`:''}${lock?'':`<button class="btn sm" data-act="ex-edit" data-id="${e.id}">${ic('edit','sm')}Editar</button>`}<button class="btn sm" data-act="ex-dup" data-id="${e.id}">${ic('copy','sm')}Duplicar</button>${lock?'':`<button class="btn sm icon ghost danger" data-act="ex-del" data-id="${e.id}" aria-label="Eliminar examen" title="Eliminar">${ic('trash','sm')}</button>`}`)}).join('')||`<div class="card empty">${ic('exam','lg')}${misEx().length?'No hay exámenes en esta categoría.':'Aún no ha creado exámenes.'}${misEx().length?'':`<button class="btn pri" data-act="ex-new">${ic('plus','sm')}Crear examen</button>`}</div>`}</div>`}
async function duplicarExamen(id){const e=clone(S.examenes.find(x=>x.id===id));
 await ocupado(null,async()=>{await rpc('guardar_examen',{p:{titulo:e.titulo+' (copia)',asignatura:e.asig,instrucciones:e.inst,apertura:'',duracion_min:e.dur,estado:'borrador',grupos:e.grupos.filter(g=>S.grupos.some(x=>x.id===g&&x.asig===e.asig)),preguntas:e.preg.map(aServidor)}});S.exFiltro='todos';closeModal();await refrescar('examenes');toast('Examen duplicado como borrador','copy')})}

/* ---------- banco ---------- */
function vBanco(){const f=S.bFiltro,q=norm(S.fBanco||''),lista=S.banco.filter(b=>(!f||b.tipo===f)&&(!q||norm(b.enun+' '+b.asig).includes(q)));
 return `${hero('Docente','Banco de preguntas','Guarde preguntas con el ícono del banco mientras crea un examen y reutilícelas sin volver a escribirlas.',`<button class="btn pri" data-act="ex-new">${ic('plus','sm')}Crear examen con el banco</button>`,'bank')}
 <div class="row"><div style="position:relative;flex:1 1 280px"><input type="search" id="f-banco" placeholder="Buscar en el banco" value="${esc(S.fBanco||'')}" aria-label="Buscar preguntas" style="padding-left:42px"><span style="position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--muted)">${ic('search','sm')}</span></div>
 <div class="seg" role="group" aria-label="Filtrar por tipo">${[['','Todas'],['sel','Selección'],['com','Completar'],['rel','Relacionar']].map(([v,l])=>`<button data-act="b-filtro" data-v="${v}" aria-pressed="${f===v}">${l}</button>`).join('')}</div></div>
 <div class="grid2">${lista.map(b=>`<article class="card ${TIPO[b.tipo][1]}" style="display:flex;flex-direction:column;gap:10px;border-top:5px solid var(--tc)"><div class="row"><span class="tag">${ic(b.tipo,'sm')}${TIPO[b.tipo][0]}</span><span class="chip">${esc(b.asig)}</span><span class="spacer"></span><span class="small muted">Usada ${b.usos} ${b.usos===1?'vez':'veces'}</span></div><p style="font-weight:600">${esc(b.enun)}</p>${(b.imgs||[]).length?`<div class="small muted">${ic('image','sm')} ${b.imgs.length} imagen${b.imgs.length>1?'es':''}</div>`:''}<div class="row" style="margin-top:auto"><button class="btn sm" data-act="b-ver" data-id="${b.id}">${ic('eye','sm')}Vista previa</button><button class="btn sm icon ghost danger" data-act="b-del" data-id="${b.id}" aria-label="Quitar del banco">${ic('trash','sm')}</button></div></article>`).join('')||`<div class="card empty">${ic('bank','lg')}${S.banco.length?'No hay preguntas con ese filtro.':'Su banco está vacío. En el editor de exámenes, use el ícono del banco en cada pregunta para guardarla aquí.'}</div>`}</div>`}
function traerBanco(){const e=S.editor,lista=S.banco.filter(b=>b.asig===e.asig);
 modal({title:'Traer preguntas del banco',icon:['bank','c4'],body:lista.length?`<p class="small muted">Preguntas de ${esc(e.asig)}. Marque las que quiere agregar.</p><ul class="list">${lista.map(b=>`<li><input type="checkbox" data-bk="${b.id}" id="bk-${b.id}" style="width:20px;height:20px;accent-color:var(--brand);flex:none"><label for="bk-${b.id}" style="flex:1;min-width:0;cursor:pointer"><span class="tag ${TIPO[b.tipo][1]}">${TIPO[b.tipo][0]}</span> <span>${esc(b.enun)}</span></label></li>`).join('')}</ul>`:`<div class="empty">${ic('bank','lg')}No tiene preguntas guardadas de ${esc(e.asig)}.</div>`,foot:`<button class="btn" data-act="close">Cancelar</button>${lista.length?`<button class="btn pri" data-act="bk-add">${ic('plus','sm')}Agregar seleccionadas</button>`:''}`})}
const datosPregunta=q=>{const c=clone(q);delete c.id;delete c.asig;delete c.docente;delete c.usos;return c};

/* ---------- editor ---------- */
function nuevaPregunta(t){const id=uid('q');if(t==='sel')return{id,tipo:'sel',valor:1,enun:'',imgs:[],opts:['','','',''],optImgs:['','','',''],ok:0};if(t==='com')return{id,tipo:'com',valor:1,enun:'',imgs:[],resp:[]};return{id,tipo:'rel',valor:1,enun:'Relacione cada elemento de la izquierda con su pareja.',imgs:[],pares:[['',''],['',''],['','']],parImgs:['','','']}}
function abrirEditor(id){const d=doc();if(!d.asig.length){toast('El administrador aún no le ha asignado asignaturas','alert');return}
 if(id){const e=S.examenes.find(x=>x.id===id);if(bloqueado(e)){modal({title:'Este examen ya fue presentado',size:'sm',icon:['lock','c2'],body:'<p>Para no alterar las notas, un examen presentado no se puede cambiar. Puede duplicarlo y corregir la copia.</p>',foot:`<button class="btn" data-act="close">Cancelar</button><button class="btn pri" data-act="ex-dup" data-id="${id}">${ic('copy','sm')}Duplicar examen</button>`});return}S.editor=clone(e)}
 else S.editor={id:null,docente:S.yo.id,titulo:'',asig:d.asig[0],grupos:[],inst:'',apertura:'',dur:60,estado:'borrador',preg:[]};S.editorErr=null;S.editorSucio=false;go('editor')}
function vEditor(){const e=S.editor,gs=misGrupos().filter(g=>g.asig===e.asig);
 return `${hero(e.id?'Editar examen':'Nuevo examen',`<span id="ed-h1">${esc(e.titulo||'Examen sin título')}</span>`,'Complete los datos, programe la fecha y agregue preguntas. Puede subir imágenes en el enunciado, en las opciones y en los pares.',`<button class="btn" data-act="ed-volver">Volver</button>`,'edit')}
 <div class="ed-layout"><div style="display:flex;flex-direction:column;gap:18px;min-width:0">
 <section class="card" style="display:flex;flex-direction:column;gap:16px"><div class="card-h" style="margin:0"><span class="chipi c1">${ic('file')}</span><h2>Datos del examen</h2></div><div class="form-grid">
  <label class="field" style="grid-column:1/-1"><span>Título</span><input type="text" id="ed-titulo" data-ed="titulo" value="${esc(e.titulo)}" placeholder="Parcial 2 · Ciclos y funciones" maxlength="120"></label>
  <label class="field"><span>Asignatura</span><select id="ed-asig">${doc().asig.map(a=>`<option ${a===e.asig?'selected':''}>${esc(a)}</option>`).join('')}</select><small class="hint">Solo aparecen las asignaturas que le asignó el administrador.</small></label>
  <fieldset class="field" style="border:0;padding:0;margin:0"><legend class="lbl" style="padding:0;margin-bottom:6px">Grupos que lo presentan</legend><div class="row">${gs.length?gs.map(g=>`<label class="chip" style="cursor:pointer;padding:9px 12px"><input type="checkbox" data-grp="${g.id}" ${e.grupos.includes(g.id)?'checked':''} style="accent-color:var(--brand)"> Grupo ${esc(g.codigo)} · ${g.est.length}</label>`).join(''):`<span class="small muted">No tiene grupos de esta asignatura. <button type="button" class="linkbtn small" data-act="nav" data-v="grupos">Crear uno</button></span>`}</div></fieldset>
  <label class="field" style="grid-column:1/-1"><span>Instrucciones (opcional)</span><textarea id="ed-inst" data-ed="inst" placeholder="Lea cada pregunta con atención." maxlength="1000">${esc(e.inst)}</textarea></label></div></section>
 <section class="card" style="display:flex;flex-direction:column;gap:16px"><div class="card-h" style="margin:0"><span class="chipi c2">${ic('cal')}</span><h2>Programación</h2></div><div class="form-grid">
  <label class="field"><span>Fecha y hora de apertura</span><input type="datetime-local" id="ed-ap" data-ed="apertura" value="${toLocalInput(e.apertura)}"></label>
  <label class="field"><span>Duración (minutos)</span><input type="number" id="ed-dur" data-ed="dur" min="5" max="300" step="5" value="${e.dur}"></label></div>
  <p class="small muted">${ic('clock','sm')} El examen es a la misma hora para todos: quien entre tarde tiene menos tiempo. Al terminar, cada estudiante puede ver las respuestas correctas.</p></section>
 <section style="display:flex;flex-direction:column;gap:14px"><div class="row"><h2>Preguntas</h2><span class="spacer"></span><span class="small muted" id="ed-tot"></span><button class="btn sm" data-act="bk-open">${ic('bank','sm')}Traer del banco</button></div>
 ${e.preg.length?e.preg.map((q,i)=>vPreguntaEdit(q,i,e.preg.length)).join(''):`<div class="card empty">${ic('exam','lg')}<b>Agregue la primera pregunta</b><span class="small">Escoja el tipo abajo o tráigala del banco. Puede mezclar los tres tipos.</span></div>`}
 <div class="add-tiles">${['sel','com','rel'].map(t=>`<button class="add-tile ${TIPO[t][1]}" data-act="q-add" data-t="${t}"><span class="chipi">${ic(t)}</span><span><b>${TIPO[t][0]}</b><small>${{sel:'Una sola respuesta correcta',com:'El estudiante escribe la palabra',rel:'Unir cada elemento con su pareja'}[t]}</small></span></button>`).join('')}</div></section>
 ${S.editorErr?`<div class="issues" role="alert"><b>Antes de programar corrija:</b><ul>${S.editorErr.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}</div>
 <aside class="ed-side"><div class="card" style="display:flex;flex-direction:column;gap:14px" id="ed-res"></div>
 <button class="btn hot" data-act="ed-save" data-m="programar" style="min-height:50px">${ic('cal','sm')}Programar examen</button><button class="btn" data-act="ed-save" data-m="borrador">${ic('save','sm')}Guardar borrador</button></aside></div>`}
function actualizarResumen(){const e=S.editor;if(!e||!$('#ed-res'))return;const tot=e.preg.reduce((a,q)=>a+(+q.valor||0),0),c=e.apertura&&+e.dur?addMin(new Date(e.apertura),+e.dur):null,n=t=>e.preg.filter(q=>q.tipo===t).length,imgs=e.preg.reduce((a,q)=>a+(q.imgs||[]).length+(q.optImgs||[]).filter(Boolean).length+(q.parImgs||[]).filter(Boolean).length,0);
 const er=validarEditor(e),chk=[['Título',!!e.titulo.trim()],['Grupo escogido',e.grupos.length>0],['Apertura y duración',!!e.apertura&&+e.dur>=5&&!er.some(x=>x.includes('pasado'))],['Preguntas completas',e.preg.length>0&&!er.some(x=>x.startsWith('Pregunta'))]],listo=chk.filter(x=>x[1]).length;
 $('#ed-res').innerHTML=`<div class="row" style="flex-wrap:nowrap">${ring(listo/4,listo===4?'var(--ok)':'var(--brand)',64,8,listo+'/4')}<div><h3>Resumen</h3><span class="small muted">${listo===4?'Listo para programar':'Faltan '+(4-listo)+' paso'+(4-listo===1?'':'s')}</span></div></div>
 <div class="row" style="gap:6px"><span class="tag ty-sel">${n('sel')} selección</span><span class="tag ty-com">${n('com')} completar</span><span class="tag ty-rel">${n('rel')} relacionar</span></div>
 <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><div class="small muted">Preguntas</div><b style="font-size:1.5rem">${e.preg.length}</b></div><div><div class="small muted">Puntos</div><b style="font-size:1.5rem">${String(tot).replace('.',',')}</b></div><div><div class="small muted">Duración</div><b>${+e.dur||0} min</b></div><div><div class="small muted">Imágenes</div><b>${imgs}</b></div></div>
 <div><div class="small muted">Termina para todos</div><b>${c?esc(fmt(c)):'—'}</b></div>
 <div style="display:flex;flex-direction:column;gap:6px;border-top:1px solid var(--line);padding-top:12px">${chk.map(([l,ok])=>`<div class="check ${ok?'':'no'}">${ic(ok?'checkc':'clock','sm')}<span>${l}</span></div>`).join('')}</div>
 <p class="small muted">Nota de 0,0 a 5,0; aprueba con ${nota1(S.cfg.aprueba)}.</p>`;
 const t=$('#ed-tot');t&&(t.textContent=`${e.preg.length} pregunta${e.preg.length===1?'':'s'} · ${String(tot).replace('.',',')} puntos`)}
function zonaImgs(q,i){const mx=S.cfg.maxImgs;return `<div class="field"><span>Imágenes del enunciado (hasta ${mx})</span>${(q.imgs||[]).length?`<div class="thumbs">${q.imgs.map((src,j)=>`<div class="thumb"><img src="${esc(src)}" alt="Imagen ${j+1} de la pregunta ${i+1}"><button class="z" data-act="zoom" data-src="q${i}-${j}" aria-label="Ampliar imagen ${j+1}"></button><button class="x" data-act="img-del" data-q="${i}" data-j="${j}" aria-label="Quitar imagen ${j+1}">${ic('x','sm')}</button></div>`).join('')}</div>`:''}
 ${(q.imgs||[]).length<mx?`<label class="drop" data-drop="${i}"><span class="chipi c1">${ic('image')}</span><span><b>Arrastre imágenes aquí o toque para elegir</b><br><span class="small muted">JPG, PNG o GIF. Se reducen solas para que carguen rápido.</span></span><input type="file" accept="image/*" multiple data-img="${i}" class="sr"></label>`:''}</div>`}
function vPreguntaEdit(q,i,n){const [tn,tc]=TIPO[q.tipo];let body='';const L='ABCDEF';
 if(q.tipo==='sel')body=`<div class="field"><span>Opciones · marque la correcta con el círculo</span>${q.opts.map((o,j)=>`<div class="opt ${q.ok===j?'is-ok':''}"><input type="radio" name="ok-${q.id}" data-q="${i}" data-okset="${j}" ${q.ok===j?'checked':''} aria-label="Marcar opción ${L[j]} como correcta"><span class="let">${L[j]}</span><input type="text" data-q="${i}" data-opt="${j}" value="${esc(o)}" placeholder="Texto de la opción ${L[j]}" aria-label="Texto de la opción ${L[j]}">
 ${q.optImgs[j]?`<span class="row" style="gap:4px;flex-wrap:nowrap"><img class="mini-img" src="${esc(q.optImgs[j])}" alt="Imagen opción ${L[j]}" data-act="zoom" data-src="o${i}-${j}"><button class="btn sm icon ghost" data-act="optimg-del" data-q="${i}" data-j="${j}" aria-label="Quitar imagen de la opción ${L[j]}">${ic('trash','sm')}</button></span>`:`<label class="btn sm icon ghost" title="Imagen para la opción ${L[j]}" style="cursor:pointer">${ic('image','sm')}<input type="file" accept="image/*" data-optimg="${i}" data-j="${j}" class="sr" aria-label="Imagen para la opción ${L[j]}"></label>`}
 <button class="btn sm icon ghost" data-act="opt-del" data-q="${i}" data-j="${j}" aria-label="Quitar opción ${L[j]}" ${q.opts.length<=2?'aria-disabled="true"':''}>${ic('x','sm')}</button></div>`).join('')}
 ${q.opts.length<6?`<button class="btn sm ghost" data-act="opt-add" data-q="${i}" style="align-self:flex-start">${ic('plus','sm')}Agregar opción</button>`:''}<small class="hint">Una opción puede ser solo imagen: deje el texto vacío y súbala con el ícono de imagen.</small></div>`;
 if(q.tipo==='com')body=`<div class="field"><span>Respuestas válidas</span><div class="row"><input type="text" id="cr-${q.id}" placeholder="Escriba una respuesta y pulse Agregar" style="flex:1 1 200px" aria-label="Nueva respuesta válida"><button class="btn sm" data-act="com-add" data-q="${i}">${ic('plus','sm')}Agregar</button></div><div class="chips">${q.resp.map((r,j)=>`<span class="chip">${esc(r)}<button data-act="com-del" data-q="${i}" data-j="${j}" aria-label="Quitar ${esc(r)}">×</button></span>`).join('')||'<span class="small muted">Aún no hay respuestas.</span>'}</div><small class="hint">Escriba ___ (tres guiones bajos) en el enunciado donde va el espacio. No importan mayúsculas ni tildes.</small></div>`;
 if(q.tipo==='rel')body=`<div class="field"><span>Pares correctos · al estudiante la columna derecha le sale en desorden</span>${q.pares.map((p,j)=>`<div class="pair"><span class="q-n" style="width:28px;height:28px;font-size:.8rem;background:${PCOL[j%PCOL.length]}">${j+1}</span><input type="text" data-q="${i}" data-par="${j}" data-lado="0" value="${esc(p[0])}" placeholder="Elemento" aria-label="Elemento ${j+1}"><span class="arrow">→</span><input type="text" data-q="${i}" data-par="${j}" data-lado="1" value="${esc(p[1])}" placeholder="Pareja" aria-label="Pareja ${j+1}">
 ${q.parImgs[j]?`<span class="row" style="gap:4px;flex-wrap:nowrap"><img class="mini-img" src="${esc(q.parImgs[j])}" alt="Imagen del elemento ${j+1}" data-act="zoom" data-src="p${i}-${j}"><button class="btn sm icon ghost" data-act="parimg-del" data-q="${i}" data-j="${j}" aria-label="Quitar imagen del elemento ${j+1}">${ic('trash','sm')}</button></span>`:`<label class="btn sm icon ghost" title="Imagen para el elemento ${j+1}" style="cursor:pointer">${ic('image','sm')}<input type="file" accept="image/*" data-parimg="${i}" data-j="${j}" class="sr" aria-label="Imagen para el elemento ${j+1}"></label>`}
 <button class="btn sm icon ghost" data-act="par-del" data-q="${i}" data-j="${j}" aria-label="Quitar par ${j+1}" ${q.pares.length<=2?'aria-disabled="true"':''}>${ic('x','sm')}</button></div>`).join('')}
 ${q.pares.length<8?`<button class="btn sm ghost" data-act="par-add" data-q="${i}" style="align-self:flex-start">${ic('plus','sm')}Agregar par</button>`:''}<small class="hint">El elemento de la izquierda puede llevar imagen. Cada par bien unido suma su parte.</small></div>`;
 return `<article class="q ${tc}"><div class="q-h"><span class="q-n">${i+1}</span><span class="tag">${ic(q.tipo,'sm')}${tn}</span><span class="spacer"></span><label class="row small" style="gap:6px;font-weight:700">Valor <input type="number" min="0.5" max="10" step="0.5" value="${q.valor}" data-q="${i}" data-val style="width:78px;min-height:36px"></label>
 <button class="btn sm icon ghost" data-act="q-prev-view" data-q="${i}" aria-label="Vista previa de la pregunta ${i+1}" title="Vista previa">${ic('eye','sm')}</button><button class="btn sm icon ghost" data-act="q-banco" data-q="${i}" aria-label="Guardar la pregunta ${i+1} en el banco" title="Guardar en el banco">${ic('bank','sm')}</button><button class="btn sm icon ghost" data-act="q-up" data-q="${i}" aria-label="Subir pregunta" ${i===0?'aria-disabled="true"':''}>${ic('up','sm')}</button><button class="btn sm icon ghost" data-act="q-down" data-q="${i}" aria-label="Bajar pregunta" ${i===n-1?'aria-disabled="true"':''}>${ic('down','sm')}</button><button class="btn sm icon ghost danger" data-act="q-del" data-q="${i}" aria-label="Eliminar pregunta ${i+1}">${ic('trash','sm')}</button></div>
 <div class="q-b"><label class="field"><span>Enunciado</span><textarea data-q="${i}" data-enun placeholder="${q.tipo==='com'?'Ejemplo: La capital de La Guajira es ___.':'Escriba la pregunta'}">${esc(q.enun)}</textarea></label>${zonaImgs(q,i)}${body}</div></article>`}
function validarEditor(e){const er=[];if(!e.titulo.trim())er.push('Escriba el título del examen.');if(!e.grupos.length)er.push('Escoja al menos un grupo.');if(!e.apertura)er.push('Indique la fecha y hora de apertura.');else if(new Date(e.apertura)<addMin(ahora(),-1))er.push('La apertura no puede quedar en el pasado.');if(!(+e.dur>=5&&+e.dur<=300))er.push('La duración debe estar entre 5 y 300 minutos.');if(!e.preg.length)er.push('Agregue al menos una pregunta.');
 e.preg.forEach((q,i)=>{const n=`Pregunta ${i+1}: `;if(!q.enun.trim())er.push(n+'falta el enunciado.');if(!(+q.valor>0))er.push(n+'el valor debe ser mayor que 0.');
  if(q.tipo==='sel'){if(q.opts.some((o,j)=>!o.trim()&&!q.optImgs[j]))er.push(n+'hay opciones sin texto ni imagen.');const t=q.opts.filter(o=>o.trim()).map(norm);if(new Set(t).size!==t.length)er.push(n+'hay opciones repetidas.')}
  if(q.tipo==='com'){if(!q.enun.includes('___'))er.push(n+'marque el espacio con ___.');if(!q.resp.length)er.push(n+'agregue al menos una respuesta válida.')}
  if(q.tipo==='rel'){if(q.pares.some((p,j)=>(!p[0].trim()&&!q.parImgs[j])||!p[1].trim()))er.push(n+'hay pares incompletos.');const d=q.pares.map(p=>norm(p[1])).filter(Boolean);if(new Set(d).size!==d.length)er.push(n+'hay parejas repetidas en la columna derecha.')}});return er}
async function guardarEditor(m,btn){const e=S.editor;
 if(m==='programar'){const er=validarEditor(e);if(er.length){S.editorErr=er;render();$('.issues').scrollIntoView({behavior:'smooth',block:'center'});return}}
 else if(!e.titulo.trim()){S.editorErr=['Escriba al menos el título para guardar el borrador.'];render();$('.issues').scrollIntoView({block:'center'});return}
 await ocupado(btn,async()=>{
  const p={id:e.id||'',titulo:e.titulo.trim(),asignatura:e.asig,instrucciones:e.inst||'',apertura:e.apertura?new Date(e.apertura).toISOString():'',duracion_min:+e.dur||60,estado:m==='programar'?'programado':'borrador',grupos:e.grupos,preguntas:e.preg.map(aServidor)};
  await rpc('guardar_examen',{p});S.editor=null;S.editorSucio=false;S.exFiltro='todos';await refrescar('examenes');
  toast(m==='programar'?'Examen programado. Los estudiantes ya lo ven en su lista.':'Borrador guardado')})}
async function subirImgs(files,fn){let n=0;for(const f of files){try{toast('Subiendo imagen…','upload');fn(await subirImagen(f));n++}catch(m){toast(mensaje(m),'alert')}}return n}
function vistaPrevia(q){const fake={resp:{},sel:null},qq=q.tipo==='rel'?{...q,...paresVista(q,'vista')}:q;modal({title:'Vista previa del estudiante',icon:['eye','c1'],body:`<div class="qcard ${TIPO[q.tipo][1]}" style="box-shadow:none"><span class="tag" style="align-self:flex-start">${ic(q.tipo,'sm')}${TIPO[q.tipo][0]}</span>${q.tipo==='com'?vCompletar(qq,fake,true):vEnunciado(qq)+vRespuesta(qq,fake,true)}</div><p class="small muted">Así verá la pregunta el estudiante. Las opciones y los pares salen en orden distinto para cada uno.</p>`,foot:'<button class="btn pri" data-act="close">Listo</button>'})}

/* ---------- resultados, sala y reportes ---------- */
function vResultados(){const e=S.examenes.find(x=>x.id===S.exSel);if(!e)return vExamenes();const r=stats(e),st=estadoExamen(e),niv=[0,0,0,0];r.filas.forEach(f=>niv[nivel(f.nota)]++);const top=r.filas.slice().sort((a,b)=>b.nota-a.nota),L='ABCDEF';
 const tipos=['sel','com','rel'].map(t=>{const ps=r.porPreg.filter(p=>p.q.tipo===t);return[t,ps.length?ps.reduce((a,p)=>a+p.pct,0)/ps.length:null]}).filter(x=>x[1]!=null);
 const noPres=[...new Set(S.grupos.filter(g=>e.grupos.includes(g.id)).flatMap(g=>g.est))].filter(id=>!S.intentos[e.id+'|'+id]);
 return `${hero('Resultados · '+esc(e.asig),esc(e.titulo),(st==='cerrado'?'Examen cerrado':'Resultados parciales: solo de quienes ya entregaron')+' · '+esc(fmt(e.apertura)),`<button class="btn" data-act="xls-res">${ic('file','sm')}Descargar Excel</button><button class="btn" data-act="nav" data-v="examenes">Volver</button>`,'chart')}
 <div class="bento">${tile('group','c1','Presentaron',r.n+'<span class="small muted"> / '+nEst(e)+'</span>')}${tile('trend','c3','Promedio',r.n?nota1(r.prom):'—',r.n?'nivel '+NIV[nivel(r.prom)].toLowerCase():'')}${tile('checkc','cok','Aprobaron',r.aprob,(r.n?Math.round(r.aprob/r.n*100):0)+' % con '+nota1(S.cfg.aprueba)+' o más')}${tile('alert','cbad','Sospechas',r.sos.length,r.sos.length?'revíselas abajo':'ninguna')}
 ${r.n?`<div class="card s5"><div class="card-h"><span class="chipi c4">${ic('target')}</span><h3>Niveles de desempeño</h3></div><div class="row" style="gap:22px">${donut(NIV.map((n,i)=>({n,v:niv[i],c:['#C0392B','#C27A0E','#2F7F8F','#1F7A4D'][i]})),150,22,'estudiantes')}<div style="display:flex;flex-direction:column;gap:8px">${NIV.map((n,i)=>`<div class="row" style="gap:8px"><span class="lv lv${i}">${n}</span><b class="mono">${niv[i]}</b></div>`).join('')}</div></div></div>
 <div class="card s7"><div class="card-h"><span class="chipi c2">${ic('grid')}</span><h3>Aciertos por tipo de pregunta</h3></div><div style="display:flex;flex-direction:column;gap:14px">${tipos.map(([t,p])=>hbar(`<span class="tag ${TIPO[t][1]}">${ic(t,'sm')}${TIPO[t][0]}</span>`,p,`var(--${t==='sel'?'a1':t==='com'?'a4':'a2'})`,Math.round(p)+' %')).join('')}</div><p class="small muted" style="margin-top:12px">Le ayuda a saber qué forma de preguntar se les dificulta más.</p></div>
 <div class="card s12"><div class="card-h"><span class="chipi cc">${ic('flag')}</span><h3>Análisis por pregunta</h3><span class="small muted">de la más fallada a la más acertada</span></div><div style="display:flex;flex-direction:column;gap:16px">${r.porPreg.slice().sort((a,b)=>a.pct-b.pct).map(p=>`<div style="display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:16px;align-items:center" class="rp">${hbar(`<span class="tag ${TIPO[p.q.tipo][1]}" style="padding:3px 7px">${e.preg.indexOf(p.q)+1}</span> ${esc(p.q.enun)}`,p.pct,p.pct<60?'var(--coral)':'var(--a3)',Math.round(p.pct)+' %')}<div>${p.dist?`<div style="display:flex;height:22px;border-radius:8px;overflow:hidden" title="Qué opción escogieron">${p.dist.map((c,j)=>c?`<span style="flex:${c};background:${j===p.q.ok?'#3FAF7A':['#E0A08A','#F2C9A0','#C9B8EE','#A8C4E6','#E8B4CF','#BFD9C9'][j]};color:#14183a;font:800 11px var(--sans);display:grid;place-items:center" title="${L[j]}: ${c}">${L[j]}</span>`:'').join('')}</div><span class="small muted">Opciones escogidas · verde = correcta</span>`:'<span class="small muted">—</span>'}</div></div>`).join('')}</div></div>`:`<div class="card s12 empty">${ic('chart','lg')}Todavía nadie ha entregado este examen.</div>`}</div>
 ${r.sos.length?`<div class="card" style="border-left:6px solid var(--bad);display:flex;flex-direction:column;gap:12px"><h3>Cerrados por sospecha</h3><p class="small muted">Revise cada caso. Si fue un error (por ejemplo, una notificación del celular) puede habilitarlo de nuevo: si el examen sigue abierto, continúa; si ya cerró, se califica con lo que alcanzó a responder.</p><ul class="list">${r.sos.map(f=>`<li>${avatar(f.s.nombre,32)}<span style="flex:1;min-width:0"><b>${esc(f.s.nombre)}</b><br><span class="small muted">${f.adv} salida${f.adv===1?'':'s'} · ${esc((f.incidentes[f.incidentes.length-1]||['',''])[1])}</span></span><button class="btn sm" data-act="seat" data-id="${f.s.id}">${ic('eye','sm')}Ver</button></li>`).join('')}</ul></div>`:''}
 ${top.length?`<div class="tbl-wrap"><table><thead><tr><th>#</th><th>Estudiante</th><th>Código</th><th class="num">Nota</th><th>Nivel</th><th>Alertas</th></tr></thead><tbody>${top.map((f,i)=>`<tr><td class="mono muted">${i+1}</td><td><div class="person">${avatar(f.s.nombre,32)}<b>${esc(f.s.nombre)}</b>${i<3&&f.nota>=4?`<span title="Cuadro de honor" style="color:var(--warn)">${ic('star','sm')}</span>`:''}</div></td><td class="mono">${esc(f.s.codigo)}</td><td class="num"><b style="font-size:1.1rem;color:${f.nota>=S.cfg.aprueba?'var(--ok)':'var(--bad)'}">${nota1(f.nota)}</b></td><td>${lvTag(f.nota)}</td><td>${f.adv?`<span class="pill p-warn"><i></i>${f.adv} advertencia${f.adv>1?'s':''}</span>`:'<span class="small muted">—</span>'}</td></tr>`).join('')}</tbody></table></div>`:''}
 ${noPres.length&&st==='cerrado'?`<div class="card"><h3>No presentaron (${noPres.length})</h3><div class="chips" style="margin-top:10px">${noPres.map(id=>`<span class="chip">${esc(estDe(id).nombre)}</span>`).join('')}</div></div>`:''}`}
function excelResultados(){const e=S.examenes.find(x=>x.id===S.exSel),r=stats(e);
 const filas=[...new Set(S.grupos.filter(g=>e.grupos.includes(g.id)).flatMap(g=>g.est))].map(id=>{const s=estDe(id),it=S.intentos[e.id+'|'+id];return{'Estudiante':s.nombre,'Código':s.codigo,'Correo':s.correo,'Programa':s.prog,'Estado':it?(it.estado==='entregado'?'Entregó':it.estado==='sospecha'?'Sospecha':'Presentando'):'No presentó','Nota':it&&it.nota!=null?it.nota:'','Nivel':it&&it.nota!=null?NIV[nivel(it.nota)]:'','Preguntas correctas':it&&it.buenas!=null?it.buenas:'','Advertencias':it?it.adv:''}});
 descargarExcel(`${e.titulo} - resultados`,[['Notas',filas],['Por pregunta',r.porPreg.map((p,i)=>({'N.°':e.preg.indexOf(p.q)+1,'Tipo':TIPO[p.q.tipo][0],'Pregunta':p.q.enun,'% de acierto':Math.round(p.pct)}))]])}
function vSala(){const e=S.examenes.find(x=>x.id===S.exSel);if(!e)return vExamenes();const ids=[...new Set(S.grupos.filter(x=>e.grupos.includes(x.id)).flatMap(x=>x.est))],rest=Math.max(0,Math.round((cierre(e)-ahora())/60000));
 const lst=ids.map(id=>{const s=estDe(id),it=S.intentos[e.id+'|'+id];let c='s-no',t='No ha entrado',p=0;if(it){if(it.estado==='entregado'){c='s-ent';t='Entregó · '+nota1(it.nota);p=1}else if(it.estado==='sospecha'){c='s-sos';t='Cerrado por sospecha';p=(it.progreso||0)/e.preg.length}else{c=it.adv?'s-adv':'s-pres';t=`Respondió ${it.progreso||0} de ${e.preg.length}`;p=(it.progreso||0)/e.preg.length}}return{s,it,c,t,p}}),cnt=k=>lst.filter(x=>x.c===k).length;
 const col={'s-pres':'var(--a1)','s-adv':'var(--warn)','s-ent':'var(--ok)','s-sos':'var(--bad)','s-no':'var(--line)'};
 return `${hero('Sala en vivo · '+esc(e.asig),esc(e.titulo),estadoExamen(e)==='en curso'?`Termina a las ${hora(cierre(e))} · quedan <b>${rest} minutos</b> · se actualiza sola cada 20 segundos`:'El examen ya no está en curso.',`<button class="btn" data-act="sala-act">${ic('clock','sm')}Actualizar</button><button class="btn" data-act="nav" data-v="examenes">Volver</button>`,'eye')}
 <div class="bento">${tile('edit','c1','Presentando',cnt('s-pres')+cnt('s-adv'))}${tile('checkc','cok','Entregaron',cnt('s-ent'))}${tile('alert','cbad','Sospecha',cnt('s-sos'))}${tile('clock','c2','No han entrado',cnt('s-no'))}</div>
 <div class="legend"><span style="--c:var(--a1)">Presentando</span><span style="--c:var(--warn)">Con advertencia</span><span style="--c:var(--ok)">Entregó</span><span style="--c:var(--bad)">Sospecha</span><span style="--c:var(--line)">No ha entrado</span></div>
 ${lst.length?`<div class="seats">${lst.map(x=>`<button class="seat ${x.c}" data-act="seat" data-id="${x.s.id}" aria-label="${esc(x.s.nombre)}: ${esc(x.t)}">${x.it&&x.it.adv?`<span class="badge" title="Advertencias">${x.it.adv}</span>`:''}<span class="top2">${ring(x.p,col[x.c],44,6)}<span class="nm">${esc(corto(x.s.nombre))}</span></span><span class="st">${esc(x.t)}</span></button>`).join('')}</div>`:`<div class="card empty">${ic('users','lg')}Los grupos de este examen no tienen estudiantes.</div>`}`}
function detalleSeat(sid){const e=S.examenes.find(x=>x.id===S.exSel),s=estDe(sid),it=S.intentos[e.id+'|'+sid];
 modal({title:s.nombre,size:'sm',icon:['user','c1'],body:`<span class="small muted">Código ${esc(s.codigo)} · ${esc(s.prog)}</span>${it?`<div class="row"><span class="pill ${it.adv?'p-warn':'p-ok'}"><i></i>${it.adv||0} advertencia${it.adv===1?'':'s'}</span></div>${it.incidentes&&it.incidentes.length?`<ul class="list">${it.incidentes.map(([h,t])=>`<li><span class="chipi cbad">${ic('alert','sm')}</span><span class="mono small" style="white-space:nowrap">${esc(h)}</span><span class="small">${esc(t)}</span></li>`).join('')}</ul>`:'<p class="muted">Sin incidentes registrados.</p>'}`:'<p class="muted">Todavía no ha entrado al examen.</p>'}
 ${it&&it.estado==='sospecha'?`<p class="small">${estadoExamen(e)==='en curso'?'Si fue un error, puede habilitarlo de nuevo. Seguirá con sus respuestas y se reinician sus advertencias.':'El examen ya cerró. Si acepta, se califica con las respuestas que alcanzó a dar.'}</p>`:''}`,foot:`<button class="btn" data-act="close">Cerrar</button>${it&&it.estado==='sospecha'?`<button class="btn pri" data-act="rehab" data-id="${sid}">${ic('checkc','sm')}${estadoExamen(e)==='en curso'?'Habilitar de nuevo':'Aceptar y calificar'}</button>`:''}`})}
async function rehabilitar(sid,btn){const it=S.intentos[S.exSel+'|'+sid];await ocupado(btn,async()=>{const r=await rpc('rehabilitar',{p_intento:it.id});closeModal();await cargarIntentosDe(S.exSel);render();toast(r==='presentando'?'Estudiante habilitado de nuevo':'Respuestas aceptadas y calificadas')})}
function vDocReportes(){const gs=misGrupos();if(!gs.length)return `${hero('Reportes del docente','Cómo va cada grupo','Evolución, niveles de desempeño y estudiantes que necesitan apoyo.','','chart')}<div class="card empty">${ic('chart','lg')}Cree grupos y aplique exámenes para ver aquí sus reportes.</div>`;
 const g=gs.find(x=>x.id===S.repGrupo)||gs[0];S.repGrupo=g.id;
 const exs=S.examenes.filter(e=>e.grupos.includes(g.id)&&estadoExamen(e)==='cerrado').sort((a,b)=>new Date(a.apertura)-new Date(b.apertura)),ests=g.est.map(estDe);
 const nota=(e,s)=>{const it=S.intentos[e.id+'|'+s.id];return it&&it.nota!=null?it.nota:null};
 const prom=s=>promedio(exs.map(e=>nota(e,s)).filter(x=>x!=null));
 const tend=s=>{const v=exs.map(e=>nota(e,s)).filter(x=>x!=null);return v.length>1?v[v.length-1]-v[0]:0};
 const proms=ests.map(s=>({s,p:prom(s),t:tend(s)})).filter(x=>x.p!=null),riesgo=proms.filter(x=>x.p<S.cfg.aprueba).sort((a,b)=>a.p-b.p),honor=proms.slice().sort((a,b)=>b.p-a.p).slice(0,3);
 const promG=exs.map(e=>stats(e).prom),gp=proms.length?proms.reduce((a,x)=>a+x.p,0)/proms.length:0;
 const tipos=['sel','com','rel'].map(t=>{let s=0,n=0;exs.forEach(e=>stats(e).porPreg.filter(p=>p.q.tipo===t).forEach(p=>{s+=p.pct;n++}));return[t,n?s/n:null]}).filter(x=>x[1]!=null);
 const comp=gs.map(x=>{const es=S.examenes.filter(e=>e.grupos.includes(x.id)&&estadoExamen(e)==='cerrado'),ps=es.map(e=>stats(e)).filter(r=>r.n).map(r=>r.prom);return{x,p:promedio(ps)}}).filter(c=>c.p!=null);
 return `${hero('Reportes del docente','Cómo va cada grupo','Evolución, niveles de desempeño y estudiantes que necesitan apoyo.',`<button class="btn" data-act="xls-rep">${ic('file','sm')}Descargar Excel</button>`,'chart')}
 <div class="seg" role="group" aria-label="Escoger grupo">${gs.map(x=>`<button data-act="rep-g" data-id="${x.id}" aria-pressed="${x.id===g.id}">${esc(x.asig)} · ${esc(x.codigo)}</button>`).join('')}</div>
 ${!exs.length?`<div class="card empty">${ic('chart','lg')}Este grupo aún no tiene exámenes cerrados.</div>`:`<div class="bento">${tile('trend','c1','Promedio del grupo',proms.length?nota1(gp):'—',proms.length?'nivel '+NIV[nivel(gp)].toLowerCase():'')}${tile('exam','c2','Exámenes cerrados',exs.length,'de este grupo')}${tile('alert','cbad','En riesgo',riesgo.length,'promedio menor que '+nota1(S.cfg.aprueba))}${tile('star','c4','Mejor promedio',honor[0]?nota1(honor[0].p):'—',honor[0]?esc(corto(honor[0].s.nombre)):'')}
 <div class="card s8"><div class="card-h"><span class="chipi c1">${ic('trend')}</span><h3>Evolución del grupo</h3></div>${linea([{n:'Promedio del grupo',c:'var(--brand)',v:promG}],exs.map(e=>fcorta(e.apertura)))}</div>
 <div class="card s4"><div class="card-h"><span class="chipi c3">${ic('group')}</span><h3>Comparación de grupos</h3></div><div style="display:flex;flex-direction:column;gap:14px">${comp.map(c=>hbar(esc(c.x.asig)+' · '+esc(c.x.codigo),c.p/5*100,NIVCOL[nivel(c.p)],nota1(c.p))).join('')}</div>
  <div style="border-top:1px solid var(--line);margin-top:16px;padding-top:14px;display:flex;flex-direction:column;gap:12px"><b class="small">Aciertos por tipo</b>${tipos.map(([t,p])=>hbar(TIPO[t][0],p,`var(--${t==='sel'?'a1':t==='com'?'a4':'a2'})`,Math.round(p)+' %')).join('')}</div></div>
 <div class="card s12"><div class="card-h"><span class="chipi c4">${ic('grid')}</span><h3>Mapa de calor · notas por estudiante</h3><div class="row" style="gap:6px">${NIV.map((n,i)=>`<span class="lv lv${i}">${n}</span>`).join('')}</div></div><div style="overflow-x:auto"><table class="heat"><thead><tr><th>Estudiante</th>${exs.map(e=>`<th title="${esc(e.titulo)}">${esc(fcorta(e.apertura))}</th>`).join('')}<th>Promedio</th><th>Tendencia</th></tr></thead><tbody>${proms.slice().sort((a,b)=>b.p-a.p).map(x=>`<tr><td><div class="person">${avatar(x.s.nombre,28)}<span style="white-space:nowrap">${esc(corto(x.s.nombre))}</span></div></td>${exs.map(e=>{const n=nota(e,x.s);return n==null?'<td class="h" style="background:var(--sunk);color:var(--muted)">—</td>':`<td class="h lv${nivel(n)}">${nota1(n)}</td>`}).join('')}<td class="h" style="background:var(--surface-2)">${nota1(x.p)}</td><td style="white-space:nowrap;font-weight:800;color:${x.t>0.05?'var(--ok)':x.t<-0.05?'var(--bad)':'var(--muted)'}">${x.t>0.05?'▲':x.t<-0.05?'▼':'●'} ${x.t>0?'+':''}${nota1(x.t)}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="card s6"><div class="card-h"><span class="chipi cbad">${ic('alert')}</span><h3>Estudiantes en riesgo</h3></div>${riesgo.length?`<ul class="list">${riesgo.map(x=>`<li>${avatar(x.s.nombre,32)}<span style="flex:1;min-width:0"><b>${esc(x.s.nombre)}</b><br><span class="small muted">Promedio ${nota1(x.p)} · ${x.t>=0?'viene mejorando':'bajó '+nota1(-x.t)}</span></span>${lvTag(x.p)}</li>`).join('')}</ul><p class="small muted" style="margin-top:10px">Sugerencia: refuerce con ellos las preguntas más falladas del último examen.</p>`:'<p class="muted">Ningún estudiante en riesgo.</p>'}</div>
 <div class="card s6"><div class="card-h"><span class="chipi c4">${ic('star')}</span><h3>Cuadro de honor</h3></div>${honor.length?`<ul class="list">${honor.map((x,i)=>`<li><span style="font:800 1.4rem var(--display);width:28px;color:${['#C27A0E','#8B93B3','#B06A3B'][i]}">${i+1}</span>${avatar(x.s.nombre,34)}<span style="flex:1;min-width:0"><b>${esc(x.s.nombre)}</b><br><span class="small muted">Promedio ${nota1(x.p)}</span></span>${lvTag(x.p)}</li>`).join('')}</ul>`:'<p class="muted">Aún no hay notas.</p>'}</div></div>`}`}
function excelReportes(){const g=S.grupos.find(x=>x.id===S.repGrupo);if(!g)return;const exs=S.examenes.filter(e=>e.grupos.includes(g.id)&&estadoExamen(e)==='cerrado').sort((a,b)=>new Date(a.apertura)-new Date(b.apertura));
 const filas=g.est.map(estDe).map(s=>{const o={'Estudiante':s.nombre,'Código':s.codigo};const v=[];exs.forEach(e=>{const it=S.intentos[e.id+'|'+s.id];const n=it&&it.nota!=null?it.nota:null;o[e.titulo]=n!=null?n:'';n!=null&&v.push(n)});const p=promedio(v);o['Promedio']=p!=null?Math.round(p*10)/10:'';o['Nivel']=p!=null?NIV[nivel(p)]:'';return o});
 descargarExcel(`${g.asig} Grupo ${g.codigo} - reporte`,[['Notas',filas]])}
