/* EVALUX · pantallas del estudiante y el examen */
const exDeEst=()=>S.examenes;
const miIntento=e=>S.intentos[e.id+'|'+S.yo.id];
function paresVista(q,seed){return{izq:q.pares.map((p,i)=>({t:p[0],img:(q.parImgs||[])[i]||''})),der:barajar(q.pares.map((p,i)=>i),seed+q.id).map(j=>({k:String(j),t:q.pares[j][1]}))}}
function vEstInicio(){const s=est(),o={'en curso':0,programado:1,cerrado:2},xs=exDeEst().slice().sort((a,b)=>o[estadoExamen(a)]-o[estadoExamen(b)]||new Date(b.apertura)-new Date(a.apertura)),ahoraEx=xs.find(e=>estadoExamen(e)==='en curso'&&(!miIntento(e)||miIntento(e).estado==='presentando'));
 const notas=xs.map(miIntento).filter(it=>it&&it.nota!=null).map(it=>it.nota),prom=promedio(notas),av=S.avisos[0],px=xs.filter(e=>estadoExamen(e)==='programado').sort((a,b)=>new Date(a.apertura)-new Date(b.apertura))[0];
 return `${hero('Estudiante','Hola, '+esc(s.nombre.split(' ')[0]),ahoraEx?`Tiene un examen disponible ahora: <b>${esc(ahoraEx.titulo)}</b>. Termina a las ${hora(cierre(ahoraEx))}.`:'Aquí aparecen los exámenes de todos sus docentes.',ahoraEx?`<button class="btn pri" data-act="est-start" data-id="${ahoraEx.id}">${ic('arrowR','sm')}${miIntento(ahoraEx)?'Continuar examen':'Presentar ahora'}</button>`:'','exam')}
 <div class="bento">${tile('exam','c2','Exámenes asignados',xs.length)}${tile('trend','c3','Su promedio',prom!=null?nota1(prom):'—',prom!=null?'nivel '+NIV[nivel(prom)].toLowerCase():'')}${tile('checkc','cok','Aprobados',notas.filter(n=>n>=S.cfg.aprueba).length,'de '+notas.length+' calificado'+(notas.length===1?'':'s'))}${tile('clock','c1','Próximo',px?`<span style="font-size:1.05rem">${esc(fmt(px.apertura))}</span>`:'—',px?esc(px.titulo):'')}
 ${av?`<div class="card s12 row" style="flex-wrap:nowrap;gap:14px;border-left:6px solid var(--coral)"><span class="chipi cc">${ic('mega')}</span><div style="flex:1;min-width:0"><b>${esc(av.titulo)}</b><p class="small muted">${esc(av.texto)}</p></div><button class="btn sm ghost" data-act="nav" data-v="avisos">Ver avisos</button></div>`:''}</div>
 <div class="grid2">${xs.map(e=>{const st=estadoExamen(e),it=miIntento(e),dd=new Date(e.apertura);let right='',acc='';
  const finTodos=e.finTodos?new Date(e.finTodos):cierre(e);
  if(it&&it.nota!=null){right=notaRoja(it.nota,86,'',it.nota>=S.cfg.aprueba);acc=ahora()>=finTodos?`<button class="btn sm pri" data-act="est-rev" data-id="${e.id}">${ic('eye','sm')}Ver respuestas</button>${lvTag(it.nota)}`:`<span class="small muted">${ic('clock','sm')} Respuestas correctas a las ${hora(finTodos)}</span>`}
  else if(it&&it.estado==='sospecha')acc='<span class="pill p-bad"><i></i>Cerrado por sospecha · hable con su docente</span>';
  else if(st==='en curso')acc=`<button class="btn sm hot" data-act="est-start" data-id="${e.id}">${ic('arrowR','sm')}${it?'Continuar examen':'Presentar examen'}</button>`;
  else if(st==='programado')acc=`<span class="pill p-info"><i></i>Abre ${esc(fmt(e.apertura))}</span>`;else acc='<span class="pill p-mute"><i></i>No lo presentó</span>';
  return `<article class="ticket" style="--tk:${TK_EX[st]}"><div class="date"><span class="d">${dd.getDate()}</span><span class="m">${mes(dd)}</span><span class="h">${hora(dd)}</span></div><div class="info"><div class="row" style="align-items:flex-start;flex-wrap:nowrap"><div style="flex:1;min-width:0;display:flex;flex-direction:column;gap:8px"><span class="chip" style="align-self:flex-start">${esc(e.asig)}</span><h3>${esc(e.titulo)}</h3><div class="meta"><span>${ic('user','sm')}${esc(corto(e.docenteNombre||''))}</span><span>${ic('exam','sm')}${nPreg(e)}</span><span>${ic('clock','sm')}${e.dur} min</span></div></div>${right}</div><div class="row">${acc}</div></div></article>`}).join('')||`<div class="card empty">${ic('exam','lg')}Aún no tiene exámenes asignados. Cuando su docente programe uno, aparecerá aquí.</div>`}</div>`}
function vProgreso(){const xs=S.progreso.slice().sort((a,b)=>new Date(a.apertura)-new Date(b.apertura));
 const mis=xs.map(x=>x.nota),grp=xs.map(x=>x.prom),prom=promedio(mis);
 const tipos=['sel','com','rel'].map(t=>{let s=0,n=0;xs.forEach(x=>{const v=(x.tipos||{})[t];if(v){s+=+v[0];n+=+v[1]}});return[t,n?s/n*100:null]}).filter(x=>x[1]!=null);
 const fuerte=tipos.slice().sort((a,b)=>b[1]-a[1])[0],debil=tipos.slice().sort((a,b)=>a[1]-b[1])[0];
 return `${hero('Estudiante','Mi progreso','Sus notas en el tiempo, comparadas con el promedio de su grupo.','','trend')}
 ${xs.length?`<div class="bento">${tile('trend','c3','Promedio',nota1(prom),'nivel '+NIV[nivel(prom)].toLowerCase())}${tile('exam','c2','Exámenes calificados',xs.length)}${tile('star','c4','Su mejor nota',nota1(Math.max(...mis)))}${tile('target','c1','Para reforzar',debil?TIPO[debil[0]][0]:'—',debil?Math.round(debil[1])+' % de aciertos':'')}
 <div class="card s8"><div class="card-h"><span class="chipi c1">${ic('trend')}</span><h3>Mis notas</h3><div class="legend"><span style="--c:var(--coral)">Mis notas</span><span style="--c:var(--a1)">Promedio del grupo</span></div></div>${linea([{n:'Mis notas',c:'var(--coral)',v:mis},{n:'Promedio del grupo',c:'var(--a1)',v:grp,dash:true}],xs.map(e=>fcorta(e.apertura)))}</div>
 <div class="card s4"><div class="card-h"><span class="chipi c4">${ic('grid')}</span><h3>Por tipo de pregunta</h3></div><div style="display:flex;flex-direction:column;gap:14px">${tipos.map(([t,p])=>hbar(TIPO[t][0],p,`var(--${t==='sel'?'a1':t==='com'?'a4':'a2'})`,Math.round(p)+' %')).join('')}</div>${fuerte?`<div class="card" style="box-shadow:none;background:var(--ok-soft);color:var(--ok);border:0;margin-top:14px;padding:12px">${ic('spark','sm')} Su fuerte: <b>${TIPO[fuerte[0]][0].toLowerCase()}</b>.</div>`:''}</div></div>
 <div class="tbl-wrap"><table><thead><tr><th>Examen</th><th>Asignatura</th><th>Fecha</th><th class="num">Nota</th><th>Nivel</th><th class="num"></th></tr></thead><tbody>${xs.slice().reverse().map(e=>`<tr><td><b>${esc(e.titulo)}</b></td><td>${esc(e.asig)}</td><td class="small">${esc(fcorta(e.apertura))}</td><td class="num"><b>${nota1(e.nota)}</b></td><td>${lvTag(e.nota)}</td><td class="num"><button class="btn sm ghost" data-act="est-rev" data-id="${e.id}">Revisar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="card empty">${ic('trend','lg')}Aquí verá su avance cuando tenga exámenes cerrados y calificados.</div>`}`}

/* ---------- presentar el examen ---------- */
const COPIA='evalux-resp-';
const guardarLocal=x=>{try{localStorage.setItem(COPIA+x.intento,JSON.stringify({resp:x.resp,flags:x.flags,t:Date.now()}))}catch(_){}};
const leerLocal=id=>{try{return JSON.parse(localStorage.getItem(COPIA+id)||'null')}catch(_){return null}};
const borrarLocal=id=>{try{localStorage.removeItem(COPIA+id)}catch(_){}};
function iniciarExamen(id){const e=S.examenes.find(x=>x.id===id);if(!e)return;if(estadoExamen(e)!=='en curso'){toast(estadoExamen(e)==='programado'?'El examen todavía no ha abierto':'El examen ya terminó','clock');return}S.exam={e,fase:'reglas',i:0,resp:{},adv:0,sel:null,flags:[],guardado:null,pend:false,incPend:[]};render();window.scrollTo({top:0})}
async function empezarExamen(btn){if(!$('#acepto').checked){$('#acepto-err').hidden=false;return}const x=S.exam;
 await ocupado(btn,async()=>{const r=await rpc('abrir_examen',{p_examen:x.e.id});
  S.off=new Date(r.ahora).getTime()-Date.now();
  x.intento=r.intento;x.cierre=new Date(r.cierre);x.maxAdv=r.max_adv;x.adv=r.advertencias||0;x.e.preg=r.preguntas;
  x.resp=r.respuestas||{};x.flags=r.marcadas||[];const loc=leerLocal(r.intento);if(loc&&loc.resp){x.resp={...x.resp,...loc.resp};x.flags=loc.flags||x.flags}
  x.orden=barajar(x.e.preg.map((q,i)=>i),est().codigo+x.e.id);x.fase='examen';
  try{const p=document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen();p&&p.catch&&p.catch(()=>{})}catch(_){}
  render();window.scrollTo({top:0})})}
function imgsHTML(q){return (q.imgs||[]).length?`<div class="qimgs">${q.imgs.map((src,j)=>`<button data-act="zoom-src" data-src="${esc(src)}" aria-label="Ampliar imagen ${j+1}"><img src="${esc(src)}" alt="Imagen de apoyo ${j+1}"></button>`).join('')}</div>`:''}
function vEnunciado(q){return `<div class="qtext">${esc(q.enun)}</div>${imgsHTML(q)}`}
function vCompletar(q,x,preview){const t=esc(q.enun).split('___');return `<div class="qtext">${t[0]}<input type="text" class="blank" ${preview?'':`data-resp="${q.id}"`} value="${esc(x.resp[q.id]||'')}" autocomplete="off" spellcheck="false" maxlength="120" aria-label="Escriba la palabra que falta">${t.slice(1).join('___')}</div>${imgsHTML(q)}<p class="small muted">Escriba la palabra que falta. No importan mayúsculas ni tildes.</p>`}
function vExam(){const x=S.exam,e=x.e,s=est();
 if(x.fase==='reglas')return `<div class="exam"><div class="exam-top"><div class="in">${MARK(32)}<div class="t"><b>${esc(e.titulo)}</b><div>${esc(e.asig)} · ${nPreg(e)} preguntas · termina a las ${hora(cierre(e))}</div></div></div></div>
 <div style="max-width:820px;width:100%;margin:0 auto;padding-block:26px;padding-inline:16px;display:flex;flex-direction:column;gap:18px">
 ${hero('Antes de empezar','Reglas del examen',e.inst?esc(e.inst):'','','shield')}
 <div class="grid2">${[['clock','c2','Un solo intento','Termina para todos a las '+hora(cierre(e))+'. Si se sale, puede volver a entrar mientras haya tiempo.'],['shield','c1','Pantalla completa','No salga de esta ventana ni cambie de pestaña.'],['alert','cbad',S.cfg.advertencias>1?'Una sola advertencia':'Sin advertencias',S.cfg.advertencias>1?`Al salir ${S.cfg.advertencias} veces, el examen se cierra como sospecha.`:'Si sale de la ventana, el examen se cierra como sospecha.'],['lock','c4','Sin copiar','No se puede copiar, pegar, imprimir ni capturar.'],['wifi','c3','Si se va el internet','Sus respuestas se guardan en este equipo y se envían al volver.'],['flag','cc','Marque para revisar','Puede señalar preguntas y volver a ellas.']].map(([i,c,t,d])=>`<div class="card row" style="flex-wrap:nowrap;align-items:flex-start;gap:14px;padding:16px"><span class="chipi ${c}">${ic(i)}</span><div><b>${t}</b><p class="small muted">${d}</p></div></div>`).join('')}</div>
 <label class="card row" style="cursor:pointer;flex-wrap:nowrap"><input type="checkbox" id="acepto" style="width:22px;height:22px;accent-color:var(--brand)"><span><b>Leí y acepto las reglas del examen.</b></span></label><p class="err" id="acepto-err" role="alert" hidden>Debe aceptar las reglas para empezar.</p>
 <div class="row"><button class="btn" data-act="exam-salir">Volver</button><span class="spacer"></span><button class="btn hot" data-act="exam-go" style="min-height:50px">${ic('arrowR','sm')}Empezar examen</button></div></div></div>`;
 if(x.fase==='sospecha')return `<div class="exam"><div style="max-width:560px;margin:12vh auto;padding-inline:16px"><div class="card" style="border-top:8px solid var(--bad);display:flex;flex-direction:column;gap:14px;padding:28px"><span class="chipi cbad" style="width:56px;height:56px">${ic('alert','lg')}</span><h1>Examen cerrado</h1><p>Salió de la ventana del examen ${x.maxAdv>1?'otra vez':''}. Sus respuestas se enviaron y el examen quedó registrado como <b>sospecha de fraude</b>.</p><p class="muted">Su docente revisará el caso y podrá habilitarlo de nuevo si fue un error.</p><button class="btn pri" data-act="exam-salir" style="align-self:flex-start">Ir a mis exámenes</button></div></div></div>`;
 const q=e.preg[x.orden[x.i]],resp=e.preg.filter(p=>respondida(p,x.resp[p.id])).length,fl=x.flags.includes(q.id),net=navigator.onLine&&!x.pend;
 return `<div class="exam" style="--qsize:${x.fs||18}px"><div class="watermark" id="wm" aria-hidden="true"></div>
 <div class="exam-top"><div class="in">${MARK(32)}<div class="t"><b>${esc(e.titulo)}</b><div>${esc(s.nombre)} · ${esc(s.codigo)}</div></div><span class="xchip ${net?'':'off'}" id="net">${ic('wifi','sm')}${net?'Conectado':'Sin conexión · guardando en el equipo'}</span><span class="xchip" id="guard">${ic('save','sm')}${x.guardado?'Guardado '+hora(x.guardado):'Guardado'}</span><div class="clock" id="clock"><span id="clock-ring"></span><span class="txt" id="timer" role="timer" aria-label="Tiempo restante">--:--</span></div></div><div class="prog"><i style="width:${resp/e.preg.length*100}%"></i></div></div>
 <div class="exam-body"><section class="qcard ${TIPO[q.tipo][1]}">
 <div class="row"><span class="q-n">${x.i+1}</span><span class="small muted">de ${e.preg.length}</span><span class="tag">${ic(q.tipo,'sm')}${TIPO[q.tipo][0]}</span><span class="spacer"></span><span class="small muted">Vale ${String(q.valor).replace('.',',')} punto${+q.valor===1?'':'s'}</span><button class="btn sm ${fl?'hot':''}" data-act="flag" aria-pressed="${fl}">${ic('flag','sm')}${fl?'Marcada':'Marcar para revisar'}</button></div>
 ${q.tipo==='com'?vCompletar(q,x):vEnunciado(q)+vRespuesta(q,x)}
 <div class="row" style="margin-top:6px;border-top:1px solid var(--line);padding-top:16px"><button class="btn" data-act="q-prev" ${x.i===0?'aria-disabled="true"':''}>Anterior</button><span class="spacer"></span>${x.i<e.preg.length-1?`<button class="btn pri" data-act="q-next">Siguiente ${ic('arrowR','sm')}</button>`:`<button class="btn hot" data-act="exam-entregar">${ic('checkc','sm')}Entregar examen</button>`}</div></section>
 <aside style="display:flex;flex-direction:column;gap:14px"><div class="card" style="padding:16px;display:flex;flex-direction:column;gap:12px"><div class="row"><b class="small" style="flex:1">Mapa de preguntas</b><span class="small muted">${resp}/${e.preg.length}</span></div><div class="qmap">${x.orden.map((pi,k)=>{const pq=e.preg[pi],d=respondida(pq,x.resp[pq.id]);return `<button class="${TIPO[pq.tipo][1]} ${d?'done':''} ${k===x.i?'cur':''} ${x.flags.includes(pq.id)?'flag':''}" data-act="q-go" data-k="${k}" aria-label="Ir a la pregunta ${k+1}${d?', respondida':''}${x.flags.includes(pq.id)?', marcada':''}">${k+1}</button>`}).join('')}</div>
 <div class="legend" style="font-size:.74rem"><span style="--c:var(--a1)">Selección</span><span style="--c:var(--a4)">Completar</span><span style="--c:var(--a2)">Relacionar</span></div>
 <div class="row" style="gap:6px"><span class="small muted" style="flex:1">Tamaño de letra</span><button class="btn sm icon" data-act="fs" data-d="-2" aria-label="Letra más pequeña">A−</button><button class="btn sm icon" data-act="fs" data-d="2" aria-label="Letra más grande">A+</button></div>
 <button class="btn hot" data-act="exam-entregar">${ic('checkc','sm')}Entregar examen</button></div></aside></div>
 ${x.aviso?`<div class="fraude" role="alertdialog" aria-labelledby="fr-t"><div class="box"><span class="chipi cbad" style="width:56px;height:56px">${ic('alert','lg')}</span><h2 id="fr-t">${x.maxAdv-x.adv===1?'Última advertencia':'Advertencia'}</h2><p>Salió de la ventana del examen. Quedó registrado.</p><p><b>${x.maxAdv-x.adv===1?'Si vuelve a salir, el examen se cerrará y se reportará como sospecha de fraude.':`Le quedan ${x.maxAdv-x.adv} salidas antes de que el examen se cierre.`}</b></p><button class="btn pri" data-act="aviso-ok" style="align-self:flex-start">Entiendo, volver al examen</button></div></div>`:''}</div>`}
function respondida(q,r){if(!q||r==null)return false;if(q.tipo==='sel')return true;if(q.tipo==='com')return String(r).trim()!=='';if(q.tipo==='rel')return Array.isArray(r)&&r.length===(q.izq||q.pares).length&&r.every(v=>v!==''&&v!=null);return false}
function vRespuesta(q,x,preview){const r=x.resp[q.id],seed=(preview?'vista':est().codigo)+q.id,L='ABCDEF';
 if(q.tipo==='sel'){const ord=barajar(q.opts.map((o,i)=>i),seed);return `<div class="choices" role="radiogroup" aria-label="Opciones">${ord.map((oi,k)=>`<label class="choice"><input type="radio" name="r-${q.id}${preview?'-pv':''}" ${preview?'':`data-resp="${q.id}"`} value="${oi}" ${r===oi?'checked':''}><span class="let">${L[k]}</span><span style="display:flex;flex-direction:column;gap:6px;min-width:0">${q.optImgs&&q.optImgs[oi]?`<img src="${esc(q.optImgs[oi])}" alt="Imagen de la opción ${L[k]}">`:''}${q.opts[oi]?`<span>${esc(q.opts[oi])}</span>`:''}</span></label>`).join('')}</div>`}
 const cur=Array.isArray(r)?r:q.izq.map(()=>''),sel=x.sel;
 return `<p class="small muted">Toque un elemento de la izquierda y luego su pareja de la derecha. Toque una pareja unida para soltarla.</p><div class="pairs"><div class="pcol"><h4>Elementos</h4>${q.izq.map((p,i)=>{const on=cur[i]!==''&&cur[i]!=null;return `<button class="pitem ${on?'on':''} ${sel===i?'sel':''}" style="--pc:${PCOL[i%PCOL.length]}" ${preview?'':`data-act="rel-left" data-i="${i}"`} aria-pressed="${sel===i}"><span class="dot">${i+1}</span>${p.img?`<img src="${esc(p.img)}" alt="${esc(p.t||'Imagen '+(i+1))}">`:''}<span>${esc(p.t)}</span></button>`}).join('')}</div>
 <div class="pcol"><h4>Parejas</h4>${q.der.map(d=>{const who=cur.findIndex(v=>v===d.k);return `<button class="pitem ${who>=0?'on':''}" style="--pc:${who>=0?PCOL[who%PCOL.length]:'var(--line)'}" ${preview?'':`data-act="rel-right" data-j="${esc(d.k)}"`} aria-label="${esc(d.t)}${who>=0?', unida con el elemento '+(who+1):''}"><span class="dot">${who>=0?who+1:'?'}</span><span>${esc(d.t)}</span></button>`}).join('')}</div></div>`}
function pintarMarca(){const w=$('#wm');if(!w)return;const s=est(),t=`${s.nombre} · ${s.codigo} · EVALUX`.replace(/[<>&'"]/g,'');w.style.backgroundImage=`url("${svgURI(`<svg xmlns='http://www.w3.org/2000/svg' width='440' height='170'><text x='10' y='95' transform='rotate(-18 220 85)' font-family='sans-serif' font-size='16' fill='#777'>${t}</text></svg>`)}")`;tick()}
function tick(){const x=S.exam;if(!x||x.fase!=='examen')return;const el=$('#timer');if(!el)return;const ms=x.cierre-ahora();if(ms<=0){if(!x.fin){x.fin=true;entregar(true)}return}const m=Math.floor(ms/60000),sg=Math.floor(ms%60000/1000);el.textContent=`${String(m).padStart(2,'0')}:${String(sg).padStart(2,'0')}`;$('#clock').classList.toggle('low',m<5);$('#clock-ring').innerHTML=ring(ms/(x.e.dur*60000),m<5?'#FFB59E':'#FFFFFF',32,5)}
function pintarRed(){const x=S.exam,c=$('#net');if(!c||!x)return;const ok=navigator.onLine&&!x.pend;c.className='xchip '+(ok?'':'off');c.innerHTML=ic('wifi','sm')+(ok?'Conectado':'Sin conexión · guardando en el equipo');const g=$('#guard');g&&(g.innerHTML=ic('save','sm')+(x.guardado?'Guardado '+hora(x.guardado):'Guardado'))}
// Guarda en el equipo al instante y en el servidor poco después
function marcarGuardado(){const x=S.exam;if(!x||!x.intento)return;guardarLocal(x);clearTimeout(marcarGuardado.t);marcarGuardado.t=setTimeout(enviarRespuestas,1200)}
async function enviarRespuestas(){const x=S.exam;if(!x||x.fase!=='examen'||x.enviando)return;x.enviando=true;
 try{while(x.incPend.length){const t=x.incPend[0];const r=await rpc('registrar_incidente',{p_intento:x.intento,p_tipo:t,p_resp:x.resp});x.incPend.shift();if(r&&r.estado==='sospecha'){x.fase='sospecha';salirPantalla();render();return}}
  const n=x.e.preg.filter(p=>respondida(p,x.resp[p.id])).length;
  const g=await rpc('guardar_respuestas',{p_intento:x.intento,p_resp:x.resp,p_marcadas:x.flags,p_respondidas:n}),st=g&&typeof g==='object'?g.estado:g;
  if(g&&g.cierre){const nc=new Date(g.cierre);if(+nc>+x.cierre)toast('Su docente le dio más tiempo','clock');x.cierre=nc}
  x.pend=false;x.guardado=new Date();
  if(st==='sospecha'){x.fase='sospecha';salirPantalla();render();return}
  if(st==='entregado'){await entregar(true);return}
 }catch(e){x.pend=true;console.warn('Sin conexión, se reintenta',e)}finally{x.enviando=false;pintarRed()}}
async function incidente(tipo){const x=S.exam;if(!x||x.fase!=='examen'||x.aviso)return;
 try{const r=await rpc('registrar_incidente',{p_intento:x.intento,p_tipo:tipo,p_resp:x.resp});x.adv=r.advertencias;x.maxAdv=r.max||x.maxAdv;
  if(r.estado==='sospecha'){x.fase='sospecha';salirPantalla();borrarLocal(x.intento);render();return}}
 catch(e){x.incPend.push(tipo);x.adv++;x.pend=true;if(x.adv>=x.maxAdv){x.fase='sospecha';salirPantalla();render();return}}
 x.aviso=true;render()}
function salirPantalla(){try{if(document.fullscreenElement)document.exitFullscreen()}catch(_){}}
async function entregar(auto){const x=S.exam;if(!x||x.entregando)return;x.entregando=true;
 try{const r=await rpc('entregar_examen',{p_intento:x.intento,p_resp:x.resp});borrarLocal(x.intento);
  S.resSel={id:x.e.id,auto,nota:r.nota==null?null:+r.nota,buenas:r.buenas,total:r.total,estado:r.estado};S.exam=null;salirPantalla();await refrescar('resultado')}
 catch(e){x.entregando=false;x.pend=true;pintarRed();
  modal({title:'No se pudo entregar',size:'sm',icon:['wifi','cbad'],body:`<p>${esc(mensaje(e))}</p><p>Sus respuestas están guardadas en este equipo. Revise la conexión y pulse <b>Entregar</b> otra vez.</p><p class="small muted">Si el tiempo se acaba sin conexión, Evalux entrega sola la última copia que alcanzó a guardar.</p>`,foot:'<button class="btn pri" data-act="close">Entendido</button>'})}}
function vEstResultado(){const r=S.resSel,e=S.examenes.find(x=>x.id===r.id)||{titulo:'',asig:''};const finR=e.finTodos?new Date(e.finTodos):e.apertura?cierre(e):null;
 if(r.estado==='sospecha')return `<div class="card empty">${ic('alert','lg')}<b>Su examen se cerró por sospecha de fraude.</b><span class="small">Hable con su docente.</span><button class="btn pri" data-act="nav" data-v="inicio">Ir a mis exámenes</button></div>`;
 const nota=r.nota||0,ok=nota>=S.cfg.aprueba;
 return `<section class="hero">${ok?`<div class="burst" aria-hidden="true">${Array.from({length:24},(_,i)=>`<i style="left:${(i*47)%100}%;top:${(i*13)%30}%;background:${PALHEX[i%6]};animation-delay:${(i%7)*.08}s"></i>`).join('')}</div>`:''}<i class="blob b1"></i><i class="blob b2"></i>
 <div class="hero-in"><div class="hero-t"><span class="eyebrow">${esc(e.asig)}</span><h1>${ok?'¡Aprobó el examen!':'Examen entregado'}</h1><p>${esc(e.titulo)}${r.auto?' · El tiempo terminó y su examen se entregó automáticamente.':''}</p>
 <div class="acts">${lvTag(nota)}${r.total?`<span class="pill p-info"><i></i>${r.buenas} de ${r.total} completamente correctas</span>`:''}</div></div>
 <div class="hoja-nota">${notaRoja(nota,170,'de 5,0',ok)}</div></div></section>
 ${finR&&ahora()<finR?`<div class="card row" style="background:var(--warn-soft);border-color:transparent;color:var(--warn);flex-wrap:nowrap;gap:14px;box-shadow:none">${ic('clock')}<span><b>Las respuestas correctas se mostrarán a las ${hora(finR)},</b> cuando termine el examen para todos sus compañeros.</span></div>`:''}
 <div class="row"><button class="btn pri" data-act="nav" data-v="inicio">Ir a mis exámenes</button>${finR&&ahora()>=finR?`<button class="btn" data-act="est-rev" data-id="${e.id}">${ic('eye','sm')}Ver respuestas</button>`:''}</div>`}
async function abrirRevision(id,btn){await ocupado(btn,async()=>{const r=await rpc('revision_examen',{p_examen:id});S.rev={...r,nota:+r.nota,preg:r.preguntas.map(aPregunta)};go('revision')})}
function vRevision(){const e=S.rev;if(!e)return vEstInicio();const ans=e.eval||{};
 return `${hero('Revisión · '+esc(e.asig),esc(e.titulo),`Nota <b>${nota1(e.nota)}</b> · ${e.buenas} de ${e.total} preguntas completamente correctas`,`<button class="btn" data-act="nav" data-v="inicio">Volver</button>`,'checkc')}
 ${e.preg.map((q,i)=>{const r=ans[q.id];let det='',ok=false;
  if(q.tipo==='sel'){ok=r===q.ok;const lab=k=>k!=null&&q.opts[k]!=null?(q.optImgs&&q.optImgs[k]?`<img class="mini-img" src="${esc(q.optImgs[k])}" alt=""> `:'')+esc(q.opts[k]):'Sin responder';det=`<p>Su respuesta: <span class="${ok?'ok-t':'bad-t'}">${lab(r)}</span></p>${ok?'':`<p>Correcta: <span class="ok-t">${lab(q.ok)}</span></p>`}`}
  if(q.tipo==='com'){ok=q.resp.some(v=>norm(v)===norm(r));det=`<p>Su respuesta: <span class="${ok?'ok-t':'bad-t'}">${r?esc(r):'Sin responder'}</span></p>${ok?'':`<p>Respuestas válidas: <span class="ok-t">${q.resp.map(esc).join(' · ')}</span></p>`}`}
  if(q.tipo==='rel'){const a=Array.isArray(r)?r:[],b=q.pares.filter((p,k)=>a[k]===k).length;ok=b===q.pares.length;det=`<div class="tbl-wrap" style="box-shadow:none"><table><tbody>${q.pares.map((p,k)=>`<tr><td>${q.parImgs&&q.parImgs[k]?`<img class="mini-img" src="${esc(q.parImgs[k])}" alt=""> `:''}<b>${esc(p[0])}</b></td><td class="${a[k]===k?'ok-t':'bad-t'}">${a[k]!=null&&q.pares[a[k]]?esc(q.pares[a[k]][1]):'Sin responder'}</td><td class="small">${a[k]===k?'Correcto':'Correcta: '+esc(p[1])}</td></tr>`).join('')}</tbody></table></div><p class="small muted">${b} de ${q.pares.length} pares correctos.</p>`}
  return `<article class="rev" style="--rc:${ok?'var(--ok)':'var(--bad)'}"><div class="row"><span class="q-n" style="background:${ok?'var(--ok)':'var(--bad)'}">${i+1}</span><span class="tag ${TIPO[q.tipo][1]}">${ic(q.tipo,'sm')}${TIPO[q.tipo][0]}</span><span class="spacer"></span><span class="pill ${ok?'p-ok':'p-bad'}"><i></i>${ok?'Correcta':'Incorrecta'}</span></div><p><b>${esc(q.enun)}</b></p>${imgsHTML(q)}${det}</article>`}).join('')}`}
